namespace ZXing
{
	public enum DecodeHintType
	{
		OTHER = 0,
		PURE_BARCODE = 1,
		POSSIBLE_FORMATS = 2,
		TRY_HARDER = 3,
		CHARACTER_SET = 4,
		ALLOWED_LENGTHS = 5,
		ASSUME_CODE_39_CHECK_DIGIT = 6,
		NEED_RESULT_POINT_CALLBACK = 7,
		ASSUME_MSI_CHECK_DIGIT = 8,
		USE_CODE_39_EXTENDED_MODE = 9,
		RELAXED_CODE_39_EXTENDED_MODE = 10,
		TRY_HARDER_WITHOUT_ROTATION = 11,
		ASSUME_GS1 = 12,
		RETURN_CODABAR_START_END = 13,
		ALLOWED_EAN_EXTENSIONS = 14
	}
}
