namespace Fabric
{
	public enum EventAction
	{
		PlaySound = 0,
		StopSound = 1,
		PauseSound = 2,
		UnpauseSound = 3,
		SetVolume = 4,
		SetPitch = 5,
		SetSwitch = 6,
		SetParameter = 7,
		SetFadeIn = 8,
		SetFadeOut = 9,
		SetPan = 10,
		AddPreset = 11,
		RemovePreset = 12,
		SetDSPParameter = 13,
		RegisterGameObject = 14,
		ResetDynamicMixer = 15,
		AdvanceSequence = 16,
		ResetSequence = 17,
		SwitchPreset = 18,
		SetTime = 19,
		SetModularSynthParameter = 20,
		StopAll = 21,
		LoadAudio = 22,
		UnloadAudio = 23,
		SetAudioClipReference = 24,
		Ignore = 25,
		SetMarker = 26,
		KeyOffMarker = 27,
		TransitionToSnapshot = 28,
		MicStart = 29,
		MicStop = 30,
		SetVolumeProperty = 31,
		SetPitchProperty = 32,
		PlayScheduled = 33,
		StopScheduled = 34,
		UnregisterGameObject = 35,
		SetGlobalParameter = 36,
		SetGlobalSwitch = 37,
		SetRegion = 38,
		QueueRegion = 39,
		FlashRegionQueue = 40
	}
}
